config/routes.rb
Mercadocamiones::Application.routes.draw do
  resources :products
  devise_for :users, :controllers => {sessions: 'sessions'}

  root :to => 'home#index'

  match '/auth/login' => 'autentificacion#login', :as => :login

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :especificaciones, :precio, :tipo, :venta, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
  has_many :products

  def self.email_exists_but_email_is_unconfirmed?(username)
    email = find_by_email(username)
    return email.email_unconfirmed? if email
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :set_msg, :current_msg

  private
  
  def set_msg str
    session[:msg] = str
  end

  def current_msg
    return session[:msg] if defined?(session[:msg])
    return ''
  end

end

app/controllers/autentificacion_controller.rb
class AutentificacionController < ApplicationController
  def login
  end

  def crear_usuario
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    if User.email_exists_but_email_is_unconfirmed?(params[:user][:email])
      set_msg t(:signed_up_but_inactive_html, :scope => 'myinfo.devise.failure', 
                  :resend_link => view_context.link_to(t(:resend_confirmation_email_link_text, :scope => 'myinfo.devise.failure'), new_user_confirmation_path)) 
    else
      self.resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
      sign_in(resource_name, resource)   
      set_msg t(:signed_in, :scope => 'devise.sessions')
      log_sign_in
    end

    respond_to do |format|
      format.js
      format.html {render :nothing => true, :status => 200, :content_type => 'text/html'}
    end
    #resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
    #sign_in_and_redirect(resource_name, resource)
  end


  def failure
    set_msg t(:invalid, :scope => 'devise.failure')   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mapping[:user]
  end

  #Sobreescribe para hacer el formato mas amigable
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg).join }
    alert_class = 'alert-error'

    #vacia los mensajes de errores que no pertenecen al recurso actual
    resource.errors.clear

    #remueve la opcion de boton cerrar por ahora - se produce un conflicto de CSS con facebook
    html = <<-HTML
<div class="alert fade in #{alert_class}">
<ul>#{messages}</ul>
</div>
HTML
    html.html_safe

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/autentificacion/_login.html.haml
= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:id => "sign_in_user"}, :format => :json, :remote => true) do |f|
  .modal-content
    .modal-header
      %h4.modal-title Iniciar sesión
    .error-messages
    
    .modal-body
      = f.input :email, :required => false, :autofocus => true, label: false, placeholder: "Correo electrónico", input_html: {class: "form-control"}
      = f.input :password, :required => false, label: false, placeholder: "Contraseña", input_html: {class: "form-control"}

    .modal-footer
  
      = f.button :submit, "Iniciar sesión", class: 'btn-primary btn-lg btn-block'

    %hr.login
      %p.footer
        ¿No tienes una cuenta? 
        =link_to "Registrate", "#", remote: true

app/views/autentificacion/login.js.erb
console.log("autentificacion/login.js.erb");
var modal = '#modal';

$('.modal-content').html('<%= j render("login") %>');
$(modal).modal();

app/views/home/index.html.haml
.container
  .row
    .col-md-3
      =render 'layouts/categorias'
    
    .col-md-7
      %h1 Productos
      %p Find me in app/views/home/index.html.haml

    .col-md-2
      =render 'layouts/social'

=render 'layouts/modal'

app/views/layouts/_categorias.html.haml
%h3 Categorias

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      =link_to "Mercado Camiones", root_path, class: 'navbar-brand'

    %nav.collapse.navbar-collapse{role: "navigation"}
      %ul.nav.navbar-nav.pull-right
        -if user_signed_in?

        -else
          %li=link_to "Ingresar", login_path, remote: true

app/views/layouts/_modal.html.haml
#modal.modal.fade
  .modal-dialog.login
    .modal-content

app/views/layouts/_social.html.haml
%h3 Social

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mercadocamiones
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    =render 'layouts/header'
    
    = yield